import express from 'express';
import multer from 'multer';
import OpenAI from 'openai';
import pg from 'pg';
import crypto from 'crypto';

const app=express(); const upload=multer({storage:multer.memoryStorage(),limits:{fileSize:20*1024*1024,files:5}});
app.use(express.json({limit:'2mb'})); app.use(express.static('public'));
const ai=new OpenAI({apiKey:process.env.OPENAI_API_KEY});
const pool=process.env.DATABASE_URL?new pg.Pool({connectionString:process.env.DATABASE_URL,ssl:process.env.DATABASE_URL.includes('localhost')?false:{rejectUnauthorized:false}}):null;
const ADMIN_KEY=process.env.ADMIN_KEY||'change-me';
const q=(s,p=[])=>pool.query(s,p);
async function init(){if(!pool)return; await q(`CREATE TABLE IF NOT EXISTS sessions(id text primary key,title text,question text,course_context text,created_at timestamptz default now()); CREATE TABLE IF NOT EXISTS submissions(id text primary key,session_id text,text_content text,artifact_name text,artifact_type text,artifact_summary text,is_meme boolean default false,created_at timestamptz default now()); CREATE TABLE IF NOT EXISTS analyses(session_id text primary key,data jsonb,updated_at timestamptz default now());`)}
const auth=(req,res,next)=>req.headers['x-admin-key']===ADMIN_KEY?next():res.status(401).json({error:'Instructor key required'});
const id=()=>crypto.randomBytes(4).toString('hex');
function parseJSON(t){try{return JSON.parse(t.replace(/^```json\s*|```$/g,''))}catch{return null}}
app.get('/api/health',(r,s)=>s.json({ok:true,db:!!pool}));
app.post('/api/sessions',auth,async(req,res)=>{if(!pool)return res.status(500).json({error:'DATABASE_URL missing'});let sid=id();await q('INSERT INTO sessions(id,title,question,course_context) VALUES($1,$2,$3,$4)',[sid,req.body.title||'Untitled activity',req.body.question||'',req.body.course_context||'']);res.json({id:sid});});
app.get('/api/sessions/:id',async(req,res)=>{let x=await q('SELECT id,title,question FROM sessions WHERE id=$1',[req.params.id]);if(!x.rows[0])return res.status(404).json({error:'Not found'});let c=await q('SELECT count(*)::int n FROM submissions WHERE session_id=$1',[req.params.id]);res.json({...x.rows[0],count:c.rows[0].n});});
app.get('/api/admin/sessions',auth,async(req,res)=>res.json((await q('SELECT s.*,count(u.id)::int submissions FROM sessions s LEFT JOIN submissions u ON u.session_id=s.id GROUP BY s.id ORDER BY s.created_at DESC')).rows));
app.post('/api/sessions/:id/submit',upload.array('files',5),async(req,res)=>{let sess=(await q('SELECT * FROM sessions WHERE id=$1',[req.params.id])).rows[0];if(!sess)return res.status(404).json({error:'Activity not found'});let text=(req.body.text||'').trim(), summaries=[];for(const f of req.files||[]){let summary=`Uploaded artifact: ${f.originalname} (${f.mimetype})`;try{let file=await ai.files.create({file:new File([f.buffer],f.originalname,{type:f.mimetype}),purpose:'user_data'});let rr=await ai.responses.create({model:process.env.OPENAI_MODEL||'gpt-5-mini',input:[{role:'user',content:[{type:'input_text',text:`Describe this student artifact neutrally for a course reflection. Extract ideas, questions, uncertainty, surprising aspects and any humor/meme meaning. Do not grade it.`},{type:'input_file',file_id:file.id}]}]});summary=rr.output_text}catch(e){summary+=` (automatic reading unavailable: ${e.message})`}summaries.push(summary)}let artifactSummary=summaries.join('\n');await q('INSERT INTO submissions(id,session_id,text_content,artifact_name,artifact_type,artifact_summary,is_meme) VALUES($1,$2,$3,$4,$5,$6,$7)',[id(),sess.id,text,(req.files||[]).map(f=>f.originalname).join(', '),(req.files||[]).map(f=>f.mimetype).join(', '),artifactSummary,req.body.is_meme==='true']);res.json({ok:true});});
app.post('/api/admin/sessions/:id/analyze',auth,async(req,res)=>{let sess=(await q('SELECT * FROM sessions WHERE id=$1',[req.params.id])).rows[0], subs=(await q('SELECT text_content,artifact_summary,is_meme FROM submissions WHERE session_id=$1 ORDER BY created_at',[req.params.id])).rows;if(!subs.length)return res.status(400).json({error:'No submissions yet'});let prompt=`You are CoursePulse, a collective reflection assistant. Never grade, rank, identify, or judge students. Synthesize the room. Activity: ${sess.question}\nCourse context: ${sess.course_context||'none'}\nSubmissions:\n${subs.map((x,i)=>`#${i+1}\n${x.text_content}\n${x.artifact_summary||''}\nStudent meme:${x.is_meme}`).join('\n')}\nReturn ONLY JSON with: room_summary (2-3 sentences), themes [{name,prevalence,description}], open_questions [string], tensions [{title,side_a,side_b}], unexpected [string], muddiest_points [{concept,signal}], missing_perspectives [string], discussion_prompts [string], student_memes [string], ai_memes [{setup,punchline,why_it_fits}], idea_landscape [{label,x,y,x_axis,y_axis}], connections [{source,target}]. Prevalence is one of many,repeated,occasional. Meme text should be playful and kind, about ideas/course content, never individual students.`;let rr=await ai.responses.create({model:process.env.OPENAI_MODEL||'gpt-5-mini',input:prompt});let data=parseJSON(rr.output_text);if(!data)return res.status(500).json({error:'Model returned invalid JSON',raw:rr.output_text});await q('INSERT INTO analyses(session_id,data) VALUES($1,$2) ON CONFLICT(session_id) DO UPDATE SET data=$2,updated_at=now()',[sess.id,data]);res.json(data);});
app.get('/api/sessions/:id/pulse',async(req,res)=>{let a=(await q('SELECT data,updated_at FROM analyses WHERE session_id=$1',[req.params.id])).rows[0];if(!a)return res.status(404).json({error:'No pulse generated yet'});res.json(a)});
app.post('/api/admin/sessions/:id/ask',auth,async(req,res)=>{let subs=(await q('SELECT text_content,artifact_summary FROM submissions WHERE session_id=$1',[req.params.id])).rows;let rr=await ai.responses.create({model:process.env.OPENAI_MODEL||'gpt-5-mini',input:`Answer ONLY from these student submissions. Be concise, aggregate, anonymous and non-evaluative. If unsupported, say so.\nSUBMISSIONS:${JSON.stringify(subs)}\nQUESTION:${req.body.question}`});res.json({answer:rr.output_text})});
init().then(()=>app.listen(process.env.PORT||3000,()=>console.log('CoursePulse running'))).catch(e=>{console.error(e);process.exit(1)});
